<?php
/**
 * Created by PhpStorm.
 * User: maltsev
 * Date: 24.10.2017
 * Time: 16:44
 */

namespace webivan\seomodule\templaters\twig;

use webivan\seomodule\templaters\Templater;
use webivan\seomodule\templaters\ITemplater;

class TwigTemplater extends Templater implements ITemplater
{
    /**
     * @property \Twig_Environment
     */
    protected $twig;

    /**
     * @inheritdoc
     */
    public function run()
    {
        $this->configureTemplater();

        return parent::run(); // TODO: Change the autogenerated stub
    }

    /**
     * Конфигурация twig
     *
     * @return void
     */
    protected function configureTemplater()
    {
        $loader = new \Twig_Loader_Array(array_map(function ($value) {
            return (string) $value;
        }, $this->parseData));

        $this->twig = new \Twig_Environment($loader);

        $this->extTwigFunctions();
    }

    /**
     * add functions twig
     *
     * @return void
     */
    protected function extTwigFunctions()
    {
        $this->twig->addExtension(new TwigFunctions());
    }

    /**
     * @inheritdoc
     */
    public function parseText($text, $key)
    {
        return $this->twig->render($key, $this->data);
    }
}